@RPTA.ProductApi_HostAddress = http://localhost:5010

GET {{RPTA.ProductApi_HostAddress}}/todos/
Accept: application/json

###

GET {{RPTA.ProductApi_HostAddress}}/todos/1
Accept: application/json

###
